from datetime import datetime
now=datetime.now()
print("full time:",now)
print("type of date:",type(now.date()))
print("date:",now.date())
print("type of month:",type(now.month))
print("month:",now.month)
print("second:",now.second)
print("day:",now.day)
print("weekday number:",now.weekday())
print("weekday:",now.strftime("%A"))
print("weekday:",now.strftime("%a"))
print("Month name:",now.strftime("%B"))
print("Month name:",now.strftime("%b"))
print(now.strftime("%B %d,%Y"))